add

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,45 +1,79 @@
-notifications:
-  email: false
-
-language: node_js
-
-node_js:
-  - "8.11.1"
-
+language: php
+dist: trusty
 sudo: false
-
-branches:
-  only:
-  - master
-  - stable
-
-if: tag IS blank
-
-before_install:
-  - curl -o- -L https://yarnpkg.com/install.sh | bash
-  - export PATH="$HOME/.yarn/bin:$PATH"
-
-install:
-  - yarn install --frozen-lockfile
 
 cache:
   yarn: true
   directories:
-    - ".cache"
-    - ".eslintcache"
-    - "node_modules"
+    - vendor
+    # Cache directory for older Composer versions.
+    - $HOME/.composer/cache/files
+    # Cache directory for more recent Composer versions.
+    - $HOME/.cache/composer/files
+
+branches:
+  only:
+    - master
+    - develop
+    - /^release\/\d+\.\d+(\.\d+)?(-\S*)?$/
+    - /^hotfix\/\d+\.\d+(\.\d+)?(-\S*)?$/
+
+matrix:
+  fast_finish: true
+  include:
+    - php: 7.3
+      env: WP_VERSION=5.0 WP_MULTISITE=1 PHPCS=1 CHECKJS=1 PHPUNIT=1 TRAVIS_NODE_VERSION=node
+    - php: 5.2
+      dist: precise
+    - php: 5.3
+      dist: precise
+    - php: 5.6
+      env: PHPUNIT=1 WP_VERSION=4.8
+    - php: 7.0
+      env: PHPUNIT=1 WP_VERSION=4.9
+    - php: nightly
+      env: PHPUNIT=1 WP_VERSION=master
+
+  allow_failures:
+    # Allow failures for unstable builds.
+    - php: nightly
+    - env: WP_VERSION=master
+
+before_install:
+- if [[ "$CHECKJS" == "1" ]]; then nvm install $TRAVIS_NODE_VERSION; fi
+- if [[ "$CHECKJS" == "1" ]]; then curl -o- -L https://yarnpkg.com/install.sh | bash; fi
+- if [[ "$CHECKJS" == "1" ]]; then export PATH=$HOME/.yarn/bin:$PATH; fi
+
+install:
+- if [[ "$PHPUNIT" == "1" ]]; then composer install --no-interaction; fi
+- if [[ "$CHECKJS" == "1" ]]; then yarn global add grunt-cli; fi
+- if [[ "$CHECKJS" == "1" ]]; then yarn install; fi
+
+before_script:
+- |
+  if [[ "$PHPUNIT" == "1" ]]; then
+    PLUGIN_SLUG=$(basename $(pwd))
+    export WP_DEVELOP_DIR=/tmp/wordpress/
+    git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
+    cd ..
+    cp -r "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
+    cd /tmp/wordpress/
+    cp wp-tests-config-sample.php wp-tests-config.php
+    sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
+    sed -i "s/yourusernamehere/travis/" wp-tests-config.php
+    sed -i "s/yourpasswordhere//" wp-tests-config.php
+    mysql -e "CREATE DATABASE wordpress_tests;" -uroot
+    cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
+    phpenv rehash
+  fi
 
 script:
-  - yarn prettier --list-different
-  - yarn lint
-  - yarn jest --maxWorkers=4
-
-after_success:
-  - yarn codecov
-
-deploy:
-  provider: script
-  script: curl -X POST -d '{}' $NETLIFY_DEPLOY_WEBHOOK && yarn semantic-release
-  skip_cleanup: true
-  on:
-    branch: master
+# Exclude tests directory from linting for PHP 5.2/3
+- if [[ $TRAVIS_PHP_VERSION == "5.2" || $TRAVIS_PHP_VERSION == "5.3" ]]; then if find -L . -path ./vendor -prune -o -path ./node_modules -prune -o -path ./tests -prune -o -name '*.php' -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi; fi
+- if [[ $TRAVIS_PHP_VERSION != "5.2" && $TRAVIS_PHP_VERSION != "5.3" ]]; then if find -L . -path ./vendor -prune -o -path ./node_modules -prune -o -name '*.php' -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi; fi
+# Run PHPCS separately for the plugin files and the test files.
+- if [[ "$PHPCS" == "1" ]]; then vendor/bin/phpcs -q --ignore=tests/* --runtime-set ignore_warnings_on_exit 1; fi
+- if [[ "$PHPCS" == "1" ]]; then vendor/bin/phpcs -q ./tests/ --runtime-set ignore_warnings_on_exit 1 --runtime-set testVersion 5.6-; fi
+- if [[ "$CHECKJS" == "1" ]]; then grunt check; fi
+- if [[ "$PHPUNIT" == "1" ]]; then composer test; fi
+- if [[ $TRAVIS_PHP_VERSION == "5.3" || $TRAVIS_PHP_VERSION == "7.3" ]]; then composer validate --no-check-all; fi
